### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by derkopp** [rg-engineering/ioBroker.sbfspot#15]
Hallo, ich versuche, auf meinem Raspi3 sbfspot zu installieren, bei Nutzung von sqlite3.
sbf wirft bei Start folgenden Fehler aus:

`Exception catch after ready [Error: Cannot find module '/opt/iobroker/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node']
`
Auf dem Raspi wurde sbf config tool verwendet.

Ich habe versucht, über
```
cd /opt/iobroker/node_modules/iobroker.sbfspot
sudo npm install
```

neu zu installieren, ohne Erfolg:

```
sudo npm install

> sqlite3@3.1.13 install /opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@8.15.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@8.15.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/lib/binding/node-v57-linux-arm"
gyp ERR! cwd /opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/lib/binding/node-v57-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.98-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/lib/binding/node-v57-linux-arm' (1)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.1" iobroker.sbfspot@2.3.2
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/iobroker.sbfspot/node_modules/sqlite3/.node-gyp"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.13 (node_modules/sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 6695 packages in 28.521s
found 13 vulnerabilities (1 low, 9 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details


```

**Comment by rg-engineering** [comment]
Ich habe das betreffende Paket in V3.0.0 durch ein anderes ersetzt. Sollte jetzt besser funktionieren...
